### PR TITLE
Update react_postprocessor.py

### PR DESCRIPTION
**Pull request by PyJulie**
It may not perfect solution but no bugs and I got some expected results.

### CODE REVIEW

**Review by zjysteven — CHANGES_REQUESTED** [review]
@PyJulie Thank you for pushing the fix. Would you mind checking if putting the assignment of `self.threshold` in `setup()` will work? If so, I would prefer this way than putting it in `postprocess()`, which incurs extra computations since `postprocess()` will be called across data batches.

**Comment by PyJulie** [comment]
Yes but only at the end of Setup() like this. As I mentioned it seems that Setup() runs first before other initialization functions.

**Comment by zjysteven** [comment]
Yes I would think so. And yes, `setup()` is expected to run first (to get activation statistics for example).

**Comment by PyJulie** [comment]
I'm not sure what goes wrong and I further look at this issue. Anyway, got the expected outcomes. Thank you for your time!

**Comment by zjysteven** [comment]
No problem. I think there were some corner cases, but the fix should be good now.

**Review by zjysteven — APPROVED** [review]

**Pull request merged**
