### PR TITLE
Add OOD detector fdbd

### PR DESCRIPTION
**Pull request by litianliu**

### CODE REVIEW

**Comment by zjysteven** [comment]
Hi thanks for opening the pull request. Would you mind adding more description of the method, e.g., the link to its publication or things like that?

**Comment by litianliu** [comment]
This is the method in [ICML2024] Fast Decision Boundary based Out-of-Distribution Detector

Original Codebase: https://github.com/litianliu/fDBD-OOD.
ICML page: https://openreview.net/forum?id=eQaOb4r6YC.

Please let me know if additional information is needed from my end.

**Comment by zjysteven** [comment]
Awesome. I would suggest also adding the method to the "Supported Methods" section in the readme https://github.com/Jingkang50/OpenOOD#supported-methods-50, which can help make it more visible.

**Comment by zjysteven** [comment]
Thanks again for the contribution!

**Comment by litianliu** [comment]
Thank you for your suggestion and help!

**Pull request merged**
