### PR TITLE
Upload ScalePostprocessors

### PR DESCRIPTION
**Pull request by kai422**
Upload ScalePostprocessors for [ICLR2024] Scaling for Training Time and Post-hoc Out-of-Distribution Detection Enhancement.

Original Codebase: https://github.com/kai422/SCALE.
ICLR page: https://openreview.net/forum?id=RDSTjtnqCg.

### CODE REVIEW

**Comment by zjysteven** [comment]
As mentioned in the issue, we will make the merge once the training code is available. BTW, You can also update the README to include a link of your method.

**Comment by kai422** [comment]
The training code has been uploaded.

Regards,
Kai

**Comment by zjysteven** [comment]
@jS5t3r Did my answer to your question in the issue solve the problem?

**Comment by jS5t3r** [comment]
@zjysteven Yes. 

In the result folder, there is no ood.csv showing up. How to fix this?

**Pull request merged**
