### PR TITLE
ImageNet-ES integration

### PR DESCRIPTION
**Pull request by Edw2n**
- ImageNet-ES is added to csid of ImageNet 1K (imagenet_fsood.yaml)
- "test_imagenet_es.txt" is needed to be added in benchmark_imglist.zip

### CODE REVIEW

**Comment by zjysteven** [comment]
Hi @Edw2n the PR looks good to me. One thing though, would you also add ImageNet-ES to [openood/evaluation_api/datasets.py](https://github.com/Jingkang50/OpenOOD/blob/dc292c81717d117ff0f6dae89ed0451be6e2c85c/openood/evaluation_api/datasets.py#L245-L361) which will integrate ImageNet-ES into the evaluation api?

**Comment by Edw2n** [comment]
Thank you for checking, @zjysteven! Currently, ImageNet-ES is included as a csid option in openood/evaluation_api/datasets.py. If there are any other additions I have missed, please let me know and I will add them!

**Comment by zjysteven** [comment]
Looks good. There are a few minor things on my end to be done to accommodate the integration (e.g. update benchmark_imglist.zip). I'm on a tight schedule this week but will try to finish them and make the merge asap (ideally by the end of this week).

**Comment by zjysteven** [comment]
Temporarily merging to a separate branch where I will add a few more commits.

**Comment by zjysteven** [comment]
Finished!

**Pull request merged**
