### PR TITLE
Update train_cifar100.sh

### PR DESCRIPTION
**Pull request by anish-lakkapragada**
I think it should be cifar100 not imagenet2000 as the dataset? 

P.S. thank you so much for open-sourcing this repository. extremely well-written code.

### CODE REVIEW

**Comment by zjysteven** [comment]
Hi @anish-lakkapragada thank you for the catch and kind words! Somehow the `cifar100/train_cifar100.sh` is for imagenet200 and `imagenet200/train_imagenet200.sh` is for cifar100. Could you make a new commit swapping their contents? This would be the most simple fix (the current commit is a little off as for CIFAR we used resnet_32x32 while resnet_224x224 is dedicated for imagenet).

**Comment by anish-lakkapragada** [comment]
@zjysteven no problem, I think I made the commits you wanted. check & lmk if everything is all good

**Comment by anish-lakkapragada** [comment]
Furthermore, 
Screenshot 2023-07-12 at 6 08 45 PM
536" alt="Screenshot 2023-07-12 at 6 08 16 PM" src="https://github.com/Jingkang50/OpenOOD/assets/68448458/4c2ea315-230d-4696-950e-99a5442df297">

the ID here for what I presume is imagenet_res50_v1.5.zip actually goes to imagenet_1k.weights.zip and maybe not imagenet_res50_v1.5.zip?

**Comment by zjysteven** [comment]
@anish-lakkapragada Thanks! Merging now.

The link contains multiple ImageNet ResNet50 weights including the torchvision one and several others (e.g., MOS, AugMix, etc.) described in [this part](https://github.com/Jingkang50/OpenOOD#v15-up-to-date) of the README. Let me know if you don't find the expected checkpoint within it :)

Closing now, but feel free to open an issue for remaining issues.

**Comment by anish-lakkapragada** [comment]
@zjysteven 



I cannot find that file in that weight zip. The code also can't either

**Comment by zjysteven** [comment]
@anish-lakkapragada Try changing the `imagenet_res50_v1.5` in the line to `imagenet1k_weights`
https://github.com/Jingkang50/OpenOOD/blob/4720467f383e8f9a0c3a50fef2bfc4aa46a3f19c/scripts/download/download.py#L72

Or simply manually unzipping the downloaded `imagenet1k_weights.zip` and you should be seeing all the checkpoints.

**Pull request merged**
